<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup Label="Library">
    <PackageVersion Include="Aspire.Hosting" Version="13.5.3" />
    <PackageVersion Include="Aspire.Hosting.SqlServer" Version="13.5.3" />
    <PackageVersion Include="SqlDataPack" Version="1.1.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>
  <ItemGroup Label="Sample">
    <PackageVersion Include="Aspire.Hosting.AppHost" Version="13.5.3" />
  </ItemGroup>
  <ItemGroup Label="Testing">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.14.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
